version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - jenkins_artifactory
    ports:
      - "49001:8080"

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.23.0
    networks:
      - jenkins_artifactory
    ports:
      - "8081:8081"

volumes:
  jenkins:
  artifactory:
networks:
  jenkins_artifactory:
